#! /bin/sh

rm -rf src/Makevars

rm -rf R/configure.R

rm -rf autom4te.cache
rm -rf ./src/Makevars
rm -rf ./src/Makedeps
rm -rf ./src/Makeconf
rm -rf ./src/*.dylib
rm -rf ./src/*.so*
rm -rf ./src/*.o
rm -rf ./src/*.d
rm -rf ./src/*.dll
rm -rf ./src/*.a
rm -rf ./src/*.rc
rm -rf ./src/*.rds
rm -rf ./src-*
