Sys.setenv("R_TESTS" = "")
library(testthat)
library(rsparse)
library(data.table)
library(Matrix)
options(rsparse_omp_threads = 1L)
futile.logger::flog.threshold(futile.logger::WARN)
data("movielens100k")
test_check("rsparse")
