library("testthat")
library("rsparse")
context("Conversion functions")

m.base = matrix(1:10, nrow=5)
m.coo = as(m.base, "TsparseMatrix")
m.coo.b = as(m.coo, "nsparseMatrix")
m.csr = as(m.base, "RsparseMatrix")
m.csr.b = as(m.csr, "nsparseMatrix")
m.csc = as(m.base, "CsparseMatrix")
m.csc.b = as(m.csc, "nsparseMatrix")
m.f32 = float::fl(m.base)
df = as.data.frame(m.base)
dt = data.table::as.data.table(df)
v.num = as.numeric(1:3)
v.int = as.integer(v.num)
v.f32 = float::fl(v.num)
v.sp = as(v.num, "dsparseVector")

test_that("Conversion to CSR", {
  expect_s4_class(as.csr.matrix(m.base), "dgRMatrix")
  expect_s4_class(as.csr.matrix(m.coo), "dgRMatrix")
  expect_s4_class(as.csr.matrix(m.coo.b), "dgRMatrix")
  expect_s4_class(as.csr.matrix(m.csr), "dgRMatrix")
  expect_s4_class(as.csr.matrix(m.csr.b), "dgRMatrix")
  expect_s4_class(as.csr.matrix(m.csc), "dgRMatrix")
  expect_s4_class(as.csr.matrix(m.csc.b), "dgRMatrix")
  expect_s4_class(as.csr.matrix(m.f32), "dgRMatrix")
  expect_s4_class(as.csr.matrix(df), "dgRMatrix")
  expect_s4_class(as.csr.matrix(dt), "dgRMatrix")
  expect_s4_class(as.csr.matrix(v.num), "dgRMatrix")
  expect_s4_class(as.csr.matrix(v.int), "dgRMatrix")
  expect_s4_class(as.csr.matrix(v.f32), "dgRMatrix")
  expect_s4_class(as.csr.matrix(v.sp), "dgRMatrix")

  expect_s4_class(as.csr.matrix(m.base, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(m.coo, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(m.coo.b, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(m.csr, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(m.csr.b, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(m.csc, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(m.csc.b, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(m.f32, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(df, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(dt, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(v.num, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(v.int, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(v.f32, binary=TRUE), "ngRMatrix")
  expect_s4_class(as.csr.matrix(v.sp, binary=TRUE), "ngRMatrix")

  expect_equal(nrow(as.csr.matrix(v.num)), 1L)
  expect_equal(nrow(as.csr.matrix(v.int)), 1L)
  expect_equal(nrow(as.csr.matrix(v.f32)), 1L)
  expect_equal(nrow(as.csr.matrix(v.sp)), 1L)

  expect_equal(dim(as.csr.matrix(m.base)), dim(m.base))
  expect_equal(dim(as.csr.matrix(m.coo)), dim(m.coo))
  expect_equal(dim(as.csr.matrix(m.coo.b)), dim(m.coo.b))
  expect_equal(dim(as.csr.matrix(m.csr)), dim(m.csr))
  expect_equal(dim(as.csr.matrix(m.csr.b)), dim(m.csr.b))
  expect_equal(dim(as.csr.matrix(m.csc)), dim(m.csc))
  expect_equal(dim(as.csr.matrix(m.csc.b)), dim(m.csc.b))
  expect_equal(dim(as.csr.matrix(m.f32)), dim(m.f32))
  expect_equal(dim(as.csr.matrix(df)), dim(df))
  expect_equal(dim(as.csr.matrix(dt)), dim(dt))
})

test_that("Conversion to CSC", {
  expect_s4_class(as.csc.matrix(m.base), "dgCMatrix")
  expect_s4_class(as.csc.matrix(m.coo), "dgCMatrix")
  expect_s4_class(as.csc.matrix(m.coo.b), "dgCMatrix")
  expect_s4_class(as.csc.matrix(m.csr), "dgCMatrix")
  expect_s4_class(as.csc.matrix(m.csr.b), "dgCMatrix")
  expect_s4_class(as.csc.matrix(m.csc), "dgCMatrix")
  expect_s4_class(as.csc.matrix(m.csc.b), "dgCMatrix")
  expect_s4_class(as.csc.matrix(m.f32), "dgCMatrix")
  expect_s4_class(as.csc.matrix(df), "dgCMatrix")
  expect_s4_class(as.csc.matrix(dt), "dgCMatrix")
  expect_s4_class(as.csc.matrix(v.num), "dgCMatrix")
  expect_s4_class(as.csc.matrix(v.int), "dgCMatrix")
  expect_s4_class(as.csc.matrix(v.f32), "dgCMatrix")
  expect_s4_class(as.csc.matrix(v.sp), "dgCMatrix")

  expect_s4_class(as.csc.matrix(m.base, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(m.coo, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(m.coo.b, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(m.csr, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(m.csr.b, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(m.csc, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(m.csc.b, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(m.f32, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(df, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(dt, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(v.num, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(v.int, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(v.f32, binary=TRUE), "ngCMatrix")
  expect_s4_class(as.csc.matrix(v.sp, binary=TRUE), "ngCMatrix")

  expect_equal(ncol(as.csc.matrix(v.num)), 1L)
  expect_equal(ncol(as.csc.matrix(v.int)), 1L)
  expect_equal(ncol(as.csc.matrix(v.f32)), 1L)
  expect_equal(ncol(as.csc.matrix(v.sp)), 1L)

  expect_equal(dim(as.csc.matrix(m.base)), dim(m.base))
  expect_equal(dim(as.csc.matrix(m.coo)), dim(m.coo))
  expect_equal(dim(as.csc.matrix(m.coo.b)), dim(m.coo.b))
  expect_equal(dim(as.csc.matrix(m.csr)), dim(m.csr))
  expect_equal(dim(as.csc.matrix(m.csr.b)), dim(m.csr.b))
  expect_equal(dim(as.csc.matrix(m.csc)), dim(m.csc))
  expect_equal(dim(as.csc.matrix(m.csc.b)), dim(m.csc.b))
  expect_equal(dim(as.csc.matrix(m.f32)), dim(m.f32))
  expect_equal(dim(as.csc.matrix(df)), dim(df))
  expect_equal(dim(as.csc.matrix(dt)), dim(dt))
})

test_that("Conversion to COO", {
  expect_s4_class(as.coo.matrix(m.base), "dgTMatrix")
  expect_s4_class(as.coo.matrix(m.coo), "dgTMatrix")
  expect_s4_class(as.coo.matrix(m.coo.b), "dgTMatrix")
  expect_s4_class(as.coo.matrix(m.csr), "dgTMatrix")
  expect_s4_class(as.coo.matrix(m.csr.b), "dgTMatrix")
  expect_s4_class(as.coo.matrix(m.csc), "dgTMatrix")
  expect_s4_class(as.coo.matrix(m.csc.b), "dgTMatrix")
  expect_s4_class(as.coo.matrix(m.f32), "dgTMatrix")
  expect_s4_class(as.coo.matrix(df), "dgTMatrix")
  expect_s4_class(as.coo.matrix(dt), "dgTMatrix")
  expect_s4_class(as.coo.matrix(v.num), "dgTMatrix")
  expect_s4_class(as.coo.matrix(v.int), "dgTMatrix")
  expect_s4_class(as.coo.matrix(v.f32), "dgTMatrix")
  expect_s4_class(as.coo.matrix(v.sp), "dgTMatrix")

  expect_s4_class(as.coo.matrix(m.base, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(m.coo, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(m.coo.b, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(m.csr, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(m.csr.b, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(m.csc, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(m.csc.b, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(m.f32, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(df, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(dt, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(v.num, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(v.int, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(v.f32, binary=TRUE), "ngTMatrix")
  expect_s4_class(as.coo.matrix(v.sp, binary=TRUE), "ngTMatrix")

  expect_equal(nrow(as.coo.matrix(v.num)), 1L)
  expect_equal(nrow(as.coo.matrix(v.int)), 1L)
  expect_equal(nrow(as.coo.matrix(v.f32)), 1L)
  expect_equal(nrow(as.coo.matrix(v.sp)), 1L)

  expect_equal(dim(as.coo.matrix(m.base)), dim(m.base))
  expect_equal(dim(as.coo.matrix(m.coo)), dim(m.coo))
  expect_equal(dim(as.coo.matrix(m.coo.b)), dim(m.coo.b))
  expect_equal(dim(as.coo.matrix(m.csr)), dim(m.csr))
  expect_equal(dim(as.coo.matrix(m.csr.b)), dim(m.csr.b))
  expect_equal(dim(as.coo.matrix(m.csc)), dim(m.csc))
  expect_equal(dim(as.coo.matrix(m.csc.b)), dim(m.csc.b))
  expect_equal(dim(as.coo.matrix(m.f32)), dim(m.f32))
  expect_equal(dim(as.coo.matrix(df)), dim(df))
  expect_equal(dim(as.coo.matrix(dt)), dim(dt))
})

test_that("Conversion through 'as'", {
  classes_to = c("dgRMatrix", "lgRMatrix", "ngRMatrix")
  for (cl in classes_to) {
    expect_s4_class(as(m.base, cl), cl)
    expect_s4_class(as(m.coo, cl), cl)
    expect_s4_class(as(m.coo.b, cl), cl)
    expect_s4_class(as(m.csc, cl), cl)
    expect_s4_class(as(m.csc.b, cl), cl)
  }
  expect_s4_class(as(m.csr, "lgRMatrix"), "lgRMatrix")
  expect_s4_class(as(m.csr, "ngRMatrix"), "ngRMatrix")
  expect_s4_class(as(m.csr.b, "lgRMatrix"), "lgRMatrix")
  expect_s4_class(as(m.csr.b, "ngRMatrix"), "ngRMatrix")
})
