# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_ftrl_weights <- function(R_model) {
    .Call('_rsparse_get_ftrl_weights', PACKAGE = 'rsparse', R_model)
}

ftrl_partial_fit <- function(m, y, R_model, weights, do_update = 1L, n_threads = 1L) {
    .Call('_rsparse_ftrl_partial_fit', PACKAGE = 'rsparse', m, y, R_model, weights, do_update, n_threads)
}

fm_create_param <- function(learning_rate_w, learning_rate_v, rank, lambda_w, lambda_v, w0_R, w_R, v_R, grad_w2_R, grad_v2_R, task, intercept) {
    .Call('_rsparse_fm_create_param', PACKAGE = 'rsparse', learning_rate_w, learning_rate_v, rank, lambda_w, lambda_v, w0_R, w_R, v_R, grad_w2_R, grad_v2_R, task, intercept)
}

fm_create_model <- function(params_ptr) {
    .Call('_rsparse_fm_create_model', PACKAGE = 'rsparse', params_ptr)
}

fill_float_matrix_randn <- function(x, stdev = 0.001) {
    invisible(.Call('_rsparse_fill_float_matrix_randn', PACKAGE = 'rsparse', x, stdev))
}

fill_float_matrix <- function(x, val) {
    invisible(.Call('_rsparse_fill_float_matrix', PACKAGE = 'rsparse', x, val))
}

fill_float_vector_randn <- function(x, stdev = 0.001) {
    invisible(.Call('_rsparse_fill_float_vector_randn', PACKAGE = 'rsparse', x, stdev))
}

fill_float_vector <- function(x, val) {
    invisible(.Call('_rsparse_fill_float_vector', PACKAGE = 'rsparse', x, val))
}

fm_partial_fit <- function(ptr, X, y, w, n_threads = 1L, do_update = 1L) {
    .Call('_rsparse_fm_partial_fit', PACKAGE = 'rsparse', ptr, X, y, w, n_threads, do_update)
}

is_invalid_ptr <- function(sexp_ptr) {
    .Call('_rsparse_is_invalid_ptr', PACKAGE = 'rsparse', sexp_ptr)
}

csr_dense_tcrossprod <- function(x_csr_r, y_transposed, num_threads = 1L) {
    .Call('_rsparse_csr_dense_tcrossprod', PACKAGE = 'rsparse', x_csr_r, y_transposed, num_threads)
}

als_implicit_double <- function(Conf, X, Y, lambda, n_threads, solver, cg_steps = 3L) {
    .Call('_rsparse_als_implicit_double', PACKAGE = 'rsparse', Conf, X, Y, lambda, n_threads, solver, cg_steps)
}

als_implicit_float <- function(Conf, XR, YR, lambda, n_threads, solver, cg_steps = 3L) {
    .Call('_rsparse_als_implicit_float', PACKAGE = 'rsparse', Conf, XR, YR, lambda, n_threads, solver, cg_steps)
}

als_loss_explicit <- function(mat, X, Y, lambda, n_threads) {
    .Call('_rsparse_als_loss_explicit', PACKAGE = 'rsparse', mat, X, Y, lambda, n_threads)
}

top_product <- function(x, y, k, n_threads, not_recommend_r) {
    .Call('_rsparse_top_product', PACKAGE = 'rsparse', x, y, k, n_threads, not_recommend_r)
}

cpp_make_sparse_approximation <- function(mat_template, X, Y, sparse_matrix_type, n_threads) {
    .Call('_rsparse_cpp_make_sparse_approximation', PACKAGE = 'rsparse', mat_template, X, Y, sparse_matrix_type, n_threads)
}

arma_svd_econ <- function(X) {
    .Call('_rsparse_arma_svd_econ', PACKAGE = 'rsparse', X)
}

