# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

als_implicit <- function(Conf, X, Y, lambda, n_threads, solver, cg_steps = 3L) {
    .Call('_reco_als_implicit', PACKAGE = 'reco', Conf, X, Y, lambda, n_threads, solver, cg_steps)
}

als_loss_explicit <- function(mat, X, Y, lambda, n_threads) {
    .Call('_reco_als_loss_explicit', PACKAGE = 'reco', mat, X, Y, lambda, n_threads)
}

dotprod_top_k <- function(x, y, k, n_threads, not_recommend) {
    .Call('_reco_dotprod_top_k', PACKAGE = 'reco', x, y, k, n_threads, not_recommend)
}

cpp_make_sparse_approximation <- function(mat_template, X, Y, sparse_matrix_type, n_threads) {
    .Call('_reco_cpp_make_sparse_approximation', PACKAGE = 'reco', mat_template, X, Y, sparse_matrix_type, n_threads)
}

arma_svd_econ <- function(X) {
    .Call('_reco_arma_svd_econ', PACKAGE = 'reco', X)
}

